"""
Anthropic LLM Adapter — placeholder implementation.
Swap in real anthropic SDK calls when API keys are configured.
"""
from __future__ import annotations

import json
from typing import List, Optional

from adapters.base import LLMAdapter


class AnthropicAdapter(LLMAdapter):
    """
    Adapter for Anthropic Claude APIs.
    Placeholder: returns deterministic mock responses for Phase 1.
    """

    def __init__(self, model: str = "claude-opus-4-6", api_key: str = "") -> None:
        self._model = model
        self._api_key = api_key

    @property
    def model_id(self) -> str:
        return self._model

    def generate(
        self,
        messages: List[dict],
        tools: Optional[List[dict]] = None,
        schema: Optional[dict] = None,
    ) -> dict:
        """
        Placeholder implementation.
        In production: replace body with `anthropic.messages.create(...)`.
        """
        last_user_msg = ""
        for m in reversed(messages):
            if m.get("role") == "user":
                last_user_msg = m.get("content", "")
                break

        # Deterministic placeholder response
        mock_content = json.dumps(
            {
                "plan_id": "placeholder-plan-id",
                "task": last_user_msg,
                "steps": [
                    "Understand the task context",
                    "Invoke appropriate tools",
                    "Validate results against schema",
                ],
                "tool_calls": [],
                "reasoning": "Placeholder plan generated by AnthropicAdapter stub.",
            }
        )

        return {
            "content": mock_content,
            "model": self._model,
            "finish_reason": "end_turn",
        }
